### PR TITLE
Add audio interface

### PR DESCRIPTION
**Pull request by felixp8**
Create interface for audio data

### CODE REVIEW

**Comment by felixp8** [comment]
waiting for clarification from Nick on dtype and whether to save the second channel which is just a constant value the whole time

**Comment by felixp8** [comment]
example file here: https://drive.google.com/file/d/1tXrOafkGdD8m76cGMThEIEWisVV-HzeU/view?usp=drive_link

**Comment by CodyCBakerPhD** [comment]
Just needs compression and should be good to go

**Comment by CodyCBakerPhD** [comment]
I'd also maybe change the name to `AudioSeries` for consistency

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
